version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

workflows:
  branch_tests:
    jobs:
      - unit_tests:
          name: Python 3.6 unit tests
          version: "3.6"
      - unit_tests:
          name: Python 3.7 unit tests
          version: "3.7"
      - static_analysis:
          name: Static analysis
jobs:

  unit_tests:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install poetry
            make dependencies
      - run:
          name: Run tests
          command: |
            make tests
  static_analysis:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install poetry
            make dependencies
      - run:
          name: Linter
          command: |
            . env/bin/activate
            make lint
      - run:
          name: Coverage
          command: |
            . env/bin/activate
            poetry run pytest --cov=pycaprio --cov-branch --cov-fail-under=90 tests/unit_tests
      - codecov/upload:
          flags: unittest

